Add modify_notes custom action
riskive/int-splunk-soar-connectors-zerofoxalerts pull request #1
Opened 2024-08-12 18:28 UTC by lderequesensS

- [ ] unit test passed
- [x] less than x (800 lines?)

## Purpose

Add new custom action to modify notes on an alert

[(Jira ticket link)](https://zf.atlassian.net/browse/ZFE-94526)

## Approach

- Add new action to zerofox_connector.py
- Change metadata on zerofox.json

## Where should the reviewer start?

zerofox_connector.py

## This PR addresses a:

- [ ] Bug
- [x] Feature
- [ ] Technical Debt
- [ ] Chore
- [ ] Vulnerability

## Quality assurance (mandatory)

Explain what you did to ensure the right behavior of the changes

## Steps to validate/test  
  
1.  Go to https://phantom.zf-integrations.com/
2. On the "Open" widget you can see alerts
3. Click one and go to "Analyst" (upper right corner)
4. Click the artifact that is there and copy the "Source ID"
5. Click "Action" (a little bit lower than Analyst)
6. On action choose "modify notes" and choose zerofox3 asset
7. Put the alert ID, choose between append or replace and write some text
8. Click "Launch"

2024-08-12 20:22 UTC, DNRRomero requested changes
se ve bien! duda, esto pasa la pipeline de splunk soar?

2024-08-12 20:22 UTC, DNRRomero commented on zerofox_connector.py
> +            new_notes = previous_notes + notes
faltaria un salto de linea o algo para separarlos, 
si las notas antiguas son
"some notes"
y las otras son 
"some other notes"

deberian quedar en lineas separadas

2024-08-12 20:41 UTC, lderequesensS commented on zerofox_connector.py
> +            new_notes = previous_notes + notes
Te refieres a dejar esto como:
```
new_notes += previous_notes
new_notes += notes
```
u otra cosa?

2024-08-12 20:48 UTC, DNRRomero commented on zerofox_connector.py
> +            new_notes = previous_notes + notes
me refiero a 
`new_notes = notes if not previous_notes else f"{previous_notes}\n{notes}"`

2024-08-12 20:49 UTC, DNRRomero commented on zerofox_connector.py
> +            new_notes = previous_notes + notes
la suma solo concatena strings, pero no considera el salto de linea

2024-08-12 21:06 UTC, DNRRomero approved these changes

2024-08-29 13:55 UTC, zkto approved these changes

2024-08-29 16:28 UTC, lderequesensS commented
Cerrado porque ya existe un PR en Splunk con este código.

2024-08-29 16:28 UTC, closed without merging